// // File: scripts/seed.ts
// import mongoose from 'mongoose';
// import { connectDB, Product, IProduct } from '../lib/db'; // Corrected import
// import { faker } from '@faker-js/faker';

// const categories = ['Shoes', 'Perfumes', 'Trousers', 'Shirts', 'T-Shirts', 'Accessories'];

// // Corrected type: We don't need _id here, as it will be generated by MongoDB
// const generateFakeProduct = (): Omit<IProduct, keyof Document | 'id'> => ({
//     name: faker.commerce.productName(),
//     description: faker.commerce.productDescription(),
//     price: parseFloat(faker.commerce.price()),
//     images: [faker.image.urlLoremFlickr({ category: 'fashion' }), faker.image.urlLoremFlickr({ category: 'fashion' })],
//     category: faker.helpers.arrayElement(categories),
//     rating: faker.number.int({ min: 1, max: 5 }),
//     reviews: [],
//     sizes: ['S', 'M', 'L', 'XL'],
//     colors: [faker.color.human(), faker.color.human(), faker.color.human()],
//     inStock: faker.datatype.boolean(),
//     createdAt: new Date(),
// });

// const seedDB = async () => {
//     try {
//         await connectDB();
//         console.log('Connected to MongoDB (seed script)');

//         await Product.deleteMany({});
//         console.log('Existing products deleted.');

//         // Generate 20 fake products
//         const products: Omit<IProduct,  keyof Document | 'id'>[] = [];
//         for (let i = 0; i < 20; i++) {
//             products.push(generateFakeProduct());
//         }

//         await Product.insertMany(products);
//         console.log('Products seeded successfully!');

//     } catch (error) {
//         console.error('Error seeding database:', error);
//         process.exit(1);
//     } finally {
//         await mongoose.disconnect();
//         console.log('Disconnected from MongoDB');
//     }
// };

 //seedDB();
